// ==UserScript==
// @name           infernal Wrapper - DTeCH
// @description    Supplies some wrapper functions for public use 
// @icon           http://eistee82.github.io/ta_simv2/icon.png
// @namespace      infernal_wrapper
// @include        https://prodgame*.alliances.commandandconquer.com/*/index.aspx*
// @updateURL      https://cdn.rawgit.com/DTeCH-X/stuff/master/DTTAIW198.meta.js
// @downloadURL    https://cdn.rawgit.com/DTeCH-X/stuff/master/DTTAIW198.user.js
// @version        2.1.1i
// @author         DTeCH, infernal_me, KRS_L, krisan
// ==/UserScript==

eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('F{(m(){3 1c=m(){3 S=16;F{3 P=m(){g(B j!="Q"){j.k(U)}L g(M.V){V.1j(U)}L{1n(U)}};m O(){j.k("A 14");P("13 1r"+1f);3 1g=$I;3 11=$I;3 5;s(3 x z $I){s(3 f z $I[x].2){g($I[x].2.1p(f)&&B $I[x].2[f]==="m"){5=$I[x].2[f].u();g(5.t("().l;3 b;s (3 d = 0 ; d < c.E ; d++){b = c[d];g((b.")>-1){$I[x].2.10=$I[x].2[f];j.k("11.1s.1t.2.10 = $I."+x+".2."+f);N}}}}s(3 f z 4.8.h.2){g(B 4.8.h.2[f]==="m"){5=4.8.h.2[f].u();g(5.t("1k")>-1&&5.t("1l")>-1){4.8.h.2.X=4.8.h.2[f];j.k("4.8.h.2.X = 4.8.h.2."+f);N}}}s(3 f z 4.8.h.2){g(B 4.8.h.2[f]==="m"){5=4.8.h.2[f].u();g(5.t("1o==7")>-1&&5.t("3 a=0;g")>-1){4.8.h.2.15=4.8.h.2[f];j.k("4.8.h.2.15 = 4.8.h.2."+f);N}}}5=4.8.v.2.W.u();3 r="s (3 b z {d:q.";3 p=5.t(r)+r.E;3 o=5.T(p,p+6);5="3 $J;y q."+o+";";3 w=K("",5);4.8.v.2.Y=w;j.k("4.8.v.2.Y = m(){3 $J;y q."+o+";}");5=4.8.v.2.W.u();r="s (3 c z {d:q.";p=5.t(r)+r.E;o=5.T(p,p+6);5="3 $J;y q."+o+";";w=K("",5);4.8.v.2.Z=w;j.k("4.8.v.2.Z = m(){3 $J;y q."+o+";}");5=4.C.n.n.2.1e.u();r="=0;s(3 a=0; (a<9); a++){q.";p=5.t(r)+r.E;o=5.T(p,p+6);5="y q."+o+";";w=K("",5);4.C.n.n.2.12=w;j.k("4.C.n.n.2.12 = m(){y q."+o+";}");g(B 4.C.n.n.2.R=="Q"){4.C.n.n.2.R=4.1h.1i.R}P("13 14")}}D(e){j.k("O: ",e)}m H(){F{g(B 1m!=="Q"){O()}L{M.17(H,18)}}D(e){S=16;j.k("H: ",e)}}g(/19\\.1a/i.1b(G.1d)){M.17(H,18)}};F{3 A=G.1u("1v");A.1w="3 S = 1x; ("+1c.u()+")();";A.1y="1z/1A";g(/19\\.1a/i.1b(G.1d)){G.1B("1C")[0].1D(A)}}D(e){j.k("A: 1E 1F: ",e)}})()}D(e){j.k("1G 1H 1I-1J 1q: ",e)}',62,108,'||prototype|var|ClientLib|strFunction|||Data|||||||key|if|CityRepair||console|log||function|Battleground|fn_name|startPos|this|searchString|for|indexOf|toString|CityUnits|fn||return|in|CCTAWrapper|typeof|Vis|catch|length|try|document|CCTAWrapper_checkIfLoaded||createHelper|Function|else|window|break|createCCTAWrapper|_log|undefined|GetNerfAndBoostModifier|CCTAWrapper_IsInstalled|slice|arguments|opera|HasUnitMdbId|CanRepair|get_OffenseUnits|get_DefenseUnits|DoStep|SharedLib|get_Simulation|wrapper|loaded|UpdateCachedFullRepairAllCost|false|setTimeout|1000|commandandconquer|com|test|CCTAWrapper_main|domain|StartBattle|PerforceChangelist|System|Base|Util|postError|DefenseSetup|DamagedEntity|qx|GM_log|Type|hasOwnProperty|Pack|loading|Combat|CbtSimulation|createElement|script|innerHTML|true|type|text|javascript|getElementsByTagName|head|appendChild|init|error|TA|Script|Bug|Fixes'.split('|'),0,{}))